[versions]
# libraries
exampleLibrary = "24.1.0"

# plugins
kotlin = "2.2.21"
changelog = "2.5.0"
intellijPlatform = "2.10.5"
qodana = "2025.2.2"
kover = "0.9.3"
junit5 = "6.0.5"

[libraries]
exampleLibrary = { group = "com.example", name = "exampleLibrary", version.ref = "exampleLibrary" }
kotestRunner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "junit5" }
kotestAssertionsCore = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "junit5" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
